import {
  IconAdjustmentsDollar,
  IconAdjustmentsExclamation,
  IconAlertTriangle,
  IconArrowRight,
  IconBell,
  IconBook,
  IconBrandGithub,
  IconBrandTwitter,
  IconBriefcase,
  IconTablePlus,
  IconBuilding,
  IconBuildingMinus,
  IconCalendar,
  IconCalendarCheck,
  IconCalendarDollar,
  IconCalendarX,
  IconCarGarage,
  IconCheck,
  IconChevronLeft,
  IconChevronRight,
  IconClock,
  IconCoin,
  IconCommand,
  IconCreditCard,
  IconCreditCardRefund,
  IconDeviceLaptop,
  IconDotsVertical,
  IconEPassport,
  IconFile,
  IconFileArrowRight,
  IconFileText,
  IconFileUpload,
  IconFireExtinguisher,
  IconFlame,
  IconFlameFilled,
  IconFoldersFilled,
  IconGasStationFilled,
  IconHelpCircle,
  IconId,
  IconLink,
  IconLayoutDashboard,
  IconLayoutKanban,
  IconLicense,
  IconLoader2,
  IconLogin,
  IconMessage,
  IconMoon,
  IconPhoto,
  IconPhotoScan,
  IconPizza,
  IconPlane,
  IconPlus,
  IconProps,
  IconReceipt,
  IconReceipt2,
  IconRoad,
  IconSettings,
  IconFolders,
  IconShield,
  IconShirt,
  IconShoppingBag,
  IconShoppingCart,
  IconSun,
  IconTemplate,
  IconTool,
  IconTrash,
  IconTruck,
  IconUser,
  IconUserCircle,
  IconUserEdit,
  IconUserPlus,
  IconUsers,
  IconInfoCircle,
  IconFilter,
  IconStopwatch,
  IconUserX,
  IconX,
  IconTicket,
  IconCashRegister,
  IconClockPause,
  IconBuildingBank,
  IconZoomCheck,
  IconCashPlus
} from '@tabler/icons-react';
import { CalendarRange, UserRoundCheck } from 'lucide-react';

export type Icon = React.ComponentType<IconProps>;

export const Icons = {
  actions: IconAdjustmentsExclamation,
  add: IconPlus,
  administratif: IconFoldersFilled,
  cashPlus: IconCashPlus,
  affectation: IconUserPlus,
  alertTriangle: IconAlertTriangle,
  bank: IconBuildingBank,
  arrowRight: IconArrowRight,
  clock: IconStopwatch,
  iconcCashRegister: IconCashRegister,
  bell: IconBell,
  billing: IconCreditCard,
  file: IconFile,
  iconTicket: IconTicket,
  pointage: IconClockPause,
  book: IconBook,
  briefcase: IconBriefcase,
  iconFilter: IconFilter,
  folder: IconFolders,
  fileUpload: IconFileUpload,
  calendar: IconCalendar,
  calendarDollar: IconCalendarDollar,
  calendarcheck: IconCalendarCheck,
  calendarx: IconCalendarX,
  camera: IconFireExtinguisher,
  car: IconCarGarage,
  calendarRange: CalendarRange,
  userRoundCheck: UserRoundCheck,
  license: IconLicense,
  check: IconCheck,
  chevronLeft: IconChevronLeft,
  fileEdit: IconFileText,
  chevronRight: IconChevronRight,
  close: IconX,
  companies: IconBuilding,
  consommation: IconAdjustmentsDollar,
  creditCard: IconCreditCardRefund,
  link: IconLink,
  currencyDollar: IconCoin,
  dashboard: IconLayoutDashboard,
  tool: IconTool,
  employee: IconUserX,
  ellipsis: IconDotsVertical,
  engine: IconFlameFilled,
  expenseNote: IconReceipt2,
  export: IconFileArrowRight,
  fileText: IconFileText,
  fileX: IconFileText,
  flame: IconFlame,
  fire: IconFlameFilled,
  fuel: IconGasStationFilled,
  garage: IconCarGarage,
  github: IconBrandGithub,
  help: IconHelpCircle,
  id: IconId,
  image: IconPhotoScan,
  filePlus: IconFileUpload,
  shuffle: IconAdjustmentsExclamation,
  import: IconFileUpload,
  kanban: IconLayoutKanban,
  laptop: IconDeviceLaptop,
  lisence: IconLicense,
  loader: IconLoader2,
  login: IconLogin,
  logo: IconCommand,
  maintenance: IconTool,
  media: IconPhoto,
  message: IconMessage,
  mileageNote: IconRoad,
  moon: IconMoon,
  my_companies: IconBuildingMinus,
  page: IconFile,
  passport: IconEPassport,
  photo: IconPhoto,
  pizza: IconPizza,
  plane: IconPlane,
  plus: IconPlus,
  post: IconFileText,
  product: IconShoppingBag,
  receipt: IconReceipt,
  info: IconInfoCircle,
  road: IconRoad,
  scale: IconCoin,
  settings: IconSettings,
  shield: IconShield,
  shirt: IconShirt,
  shoppingBag: IconShoppingBag,
  shoppingCart: IconShoppingCart,
  spinner: IconLoader2,
  sun: IconSun,
  template: IconTemplate,
  IconTablePlus: IconTablePlus,
  trash: IconTrash,
  truck: IconTruck,
  twitter: IconBrandTwitter,
  user: IconUser,
  user2: IconUserCircle,
  userPen: IconUserEdit,
  users: IconUsers,
  zoom: IconZoomCheck
};
